"""empty message

Revision ID: 16e9bbd382da
Revises: abe5c30caeed
Create Date: 2026-05-11 13:28:52.491229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e9bbd382da'
down_revision = 'abe5c30caeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_seconds', sa.Integer(), nullable=True))
        batch_op.drop_column('study_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_hours', sa.FLOAT(), nullable=True))
        batch_op.drop_column('study_seconds')

    # ### end Alembic commands ###
