"""initial schema

<<<<<<<< HEAD:migrations/versions/81789185071a_.py
Revision ID: 81789185071a
Revises: 
Create Date: 2026-05-06 22:48:45.783260
========
Revision ID: 0c3bb04db94f
Revises: 
Create Date: 2026-05-06 11:19:29.794011
>>>>>>>> 39b5ed23b91ff02e9e8ed4011e8bd50c1a311a5d:migrations/versions/0c3bb04db94f_addedTimerSessionandSettingsTables.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/81789185071a_.py
revision = '81789185071a'
========
revision = '0c3bb04db94f'
>>>>>>>> 39b5ed23b91ff02e9e8ed4011e8bd50c1a311a5d:migrations/versions/0c3bb04db94f_addedTimerSessionandSettingsTables.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('study_hours', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_restratio', sa.Integer(), nullable=False),
    sa.Column('pom_restratio', sa.Integer(), nullable=False),
    sa.Column('pom_worklength', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timer_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('taskforsession', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['taskforsession'], ['task.content'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer_session')
    op.drop_table('task')
    op.drop_table('settings')
    op.drop_table('user')
    # ### end Alembic commands ###
