"""empty message

Revision ID: 8b127753d365
Revises: 81789185071a
Create Date: 2026-05-07 00:38:23.785671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b127753d365'
down_revision = '81789185071a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_restratio', sa.Integer(), nullable=False),
    sa.Column('pom_restratio', sa.Integer(), nullable=False),
    sa.Column('pom_worklength', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timer_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('taskforsession_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['taskforsession_id'], ['task.content'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer_session')
    op.drop_table('settings')
    # ### end Alembic commands ###
