"""empty message

Revision ID: abe5c30caeed
Revises: 
Create Date: 2026-05-11 12:28:34.559080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abe5c30caeed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('study_hours', sa.Float(), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_restratio', sa.Integer(), nullable=False),
    sa.Column('pom_worklength', sa.Integer(), nullable=False),
    sa.Column('pom_short_break', sa.Integer(), nullable=False),
    sa.Column('pom_long_break', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timer_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('taskforsession', sa.String(length=128), nullable=False),
    sa.Column('sessiondate', sa.String(length=10), nullable=False),
    sa.Column('timeCost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['taskforsession'], ['task.content'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer_session')
    op.drop_table('task')
    op.drop_table('settings')
    op.drop_table('user')
    # ### end Alembic commands ###
