"""changed date in timerSession table to a string for sqlite query usage

Revision ID: c0b1191541bc
Revises: 0c3bb04db94f
Create Date: 2026-05-08 18:04:04.120381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b1191541bc'
down_revision = '0c3bb04db94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sessiondate', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('timeCost', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer_session', schema=None) as batch_op:
        batch_op.drop_column('timeCost')
        batch_op.drop_column('sessiondate')

    # ### end Alembic commands ###
