"""make start_time and end_time nullable

Revision ID: cd6009e199e4
Revises: b2c3d4e5f6a7
Create Date: 2026-05-15 22:12:03.291523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6009e199e4'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer_session', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timer_session', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
