"""empty message

Revision ID: df1b202ee3d1
Revises: fc04abd4af19
Create Date: 2026-05-09 23:22:39.107394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df1b202ee3d1'
down_revision = 'fc04abd4af19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pom_short_break', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('pom_long_break', sa.Integer(), nullable=False))
        batch_op.drop_column('pom_restratio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pom_restratio', sa.INTEGER(), nullable=False))
        batch_op.drop_column('pom_long_break')
        batch_op.drop_column('pom_short_break')

    # ### end Alembic commands ###
