"""created main database

Revision ID: fce3c6e7dd22
Revises: 3dc001f9b9d8
Create Date: 2026-05-03 19:59:52.849187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce3c6e7dd22'
down_revision = '3dc001f9b9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tasks',
    sa.Column('email', sa.Integer(), nullable=False),
    sa.Column('subjects', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('timer_session',
    sa.Column('email', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('content', sa.VARCHAR(length=128), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False)
    )
    op.drop_table('timer_session')
    op.drop_table('tasks')
    op.drop_table('user')
    # ### end Alembic commands ###
